apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: payment-secret

spec:
  refreshInterval: 1m

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: payment-secret

  data:
  - secretKey: API_TOKEN
    remoteRef:
      key: payment-secret
      property: API_TOKEN
