apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-app-script

data:
  app.sh: |
    #!/bin/sh

    echo "Starting Payment Service..."

    while true
    do
      echo "Connecting to Redis..."

      RESULT=$(redis-cli \
        -h redis-master \
        -a "$REDIS_PASSWORD" \
        PING 2>&1)

      echo "$RESULT"

      if echo "$RESULT" | grep -q "PONG"; then
        echo "Redis connection successful"
      else
        echo "Cannot connect to Redis"
        echo "HTTP 503 Service Unavailable"
      fi

      sleep 10
    done
