apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: default

spec:
  refreshInterval: 1m

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: redis-secret
    creationPolicy: Owner

  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: redis-secret
      property: REDIS_PASSWORD
