apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "payment-service healthy"
            sleep 30
          done
