apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-app-secret
  namespace: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: payment-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: payment-app-secret
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: payment-app-secret
        property: DB_PASSWORD

    - secretKey: JWT_SECRET
      remoteRef:
        key: payment-app-secret
        property: JWT_SECRET
